export type TaskStatusCode = 'ACT' | 'AWI' | 'ISS' | 'EXC' | 'COM'
export type TaskSkillCode = 'RFJBAS' | 'RFTTC1' | 'RFTTC2' | 'RISDN1' | 'RISDN2' | 'RFTTP' | 'FED1' | 'OGGA1' | 'OGGA2' | 'SOGEA'
export type TaskResponseCode = 'SH01' | 'SH02' | 'SHP3' | 'SH04' | 'NONE'
export type TaskCommitType = 'APPOINTMENT' | 'START BY' | 'COMPLETE BY' | 'TAIL'
export type TaskDomainId = 'ZA' | 'ZB' | 'ZC' | 'ZE' | 'MG' | 'MF' | 'MH'

export const TASK_STATUS_LABELS: Record<TaskStatusCode, string> = {
  ACT: 'Active',
  AWI: 'Awaiting info',
  ISS: 'Issue',
  EXC: 'Executing',
  COM: 'Complete',
}

export interface TaskTableRow {
  taskId: string
  status: TaskStatusCode
  primarySkill: TaskSkillCode
  capabilities: TaskSkillCode[]
  responseCode: TaskResponseCode
  linkedTask: 'Y' | 'N'
  commitType: TaskCommitType
  commitDate: string
  workId: string
  domainId: TaskDomainId
  impactScore: number
  resourceId: string
  resourceName: string
  division: 'Service Delivery' | 'Complex Engineering' | 'Admin'
  postCode: string
  updatedAt: string
}

export const TASK_TABLE_ROWS: TaskTableRow[] = [
  {
    taskId: 'RG-TH049021',
    status: 'ACT',
    primarySkill: 'RFTTP',
    capabilities: ['RFTTP', 'FED1'],
    responseCode: 'SH01',
    linkedTask: 'N',
    commitType: 'APPOINTMENT',
    commitDate: '2026-01-03T00:00:00Z',
    workId: 'OGEA0156887',
    domainId: 'ZA',
    impactScore: 500,
    resourceId: 'SWBXR36',
    resourceName: 'Delta Team',
    division: 'Service Delivery',
    postCode: 'CF44 8LF',
    updatedAt: '2026-01-03T08:15:00Z',
  },
  {
    taskId: 'RG-TH049118',
    status: 'AWI',
    primarySkill: 'RFTTC1',
    capabilities: ['RFTTC1', 'RFJBAS'],
    responseCode: 'SH02',
    linkedTask: 'Y',
    commitType: 'START BY',
    commitDate: '2026-01-04T00:00:00Z',
    workId: 'OGEA0157123',
    domainId: 'ZB',
    impactScore: 275,
    resourceId: 'SWQJX19',
    resourceName: 'Ops Pair 19',
    division: 'Service Delivery',
    postCode: 'CF10 2HQ',
    updatedAt: '2026-01-03T06:45:00Z',
  },
  {
    taskId: 'RG-TR598201',
    status: 'ISS',
    primarySkill: 'RISDN2',
    capabilities: ['RISDN1', 'RISDN2'],
    responseCode: 'SHP3',
    linkedTask: 'N',
    commitType: 'COMPLETE BY',
    commitDate: '2026-01-05T00:00:00Z',
    workId: 'OGGA0177123',
    domainId: 'ZE',
    impactScore: 120,
    resourceId: 'SWBLN04',
    resourceName: '',
    division: 'Complex Engineering',
    postCode: 'CF62 3AB',
    updatedAt: '2026-01-02T19:30:00Z',
  },
  {
    taskId: 'RG-MN883210',
    status: 'EXC',
    primarySkill: 'OGGA2',
    capabilities: ['OGGA1', 'OGGA2'],
    responseCode: 'SH04',
    linkedTask: 'Y',
    commitType: 'TAIL',
    commitDate: '2026-01-06T00:00:00Z',
    workId: 'OGGA0199881',
    domainId: 'MG',
    impactScore: 50,
    resourceId: 'SWZTR08',
    resourceName: 'Field Hub 8',
    division: 'Complex Engineering',
    postCode: 'CF82 7EE',
    updatedAt: '2026-01-02T16:05:00Z',
  },
  {
    taskId: 'RG-QL772910',
    status: 'COM',
    primarySkill: 'SOGEA',
    capabilities: ['SOGEA'],
    responseCode: 'NONE',
    linkedTask: 'N',
    commitType: 'COMPLETE BY',
    commitDate: '2026-01-03T00:00:00Z',
    workId: 'SOGE0190123',
    domainId: 'MF',
    impactScore: 999,
    resourceId: 'SWMME21',
    resourceName: 'QA Cell 21',
    division: 'Admin',
    postCode: 'CF31 3RT',
    updatedAt: '2026-01-03T05:55:00Z',
  },
  {
    taskId: 'RG-ZN441203',
    status: 'ACT',
    primarySkill: 'RFJBAS',
    capabilities: ['RFJBAS', 'RFTTC1'],
    responseCode: 'SH02',
    linkedTask: 'N',
    commitType: 'APPOINTMENT',
    commitDate: '2026-01-07T00:00:00Z',
    workId: 'OGEA0177888',
    domainId: 'ZC',
    impactScore: 610,
    resourceId: 'SWAVE11',
    resourceName: 'Alpha Pair 11',
    division: 'Service Delivery',
    postCode: 'CF45 4PL',
    updatedAt: '2026-01-03T09:05:00Z',
  },
  {
    taskId: 'RG-LP220977',
    status: 'AWI',
    primarySkill: 'RISDN1',
    capabilities: ['RISDN1', 'RISDN2'],
    responseCode: 'SH01',
    linkedTask: 'Y',
    commitType: 'START BY',
    commitDate: '2026-01-08T00:00:00Z',
    workId: 'OGGA0188222',
    domainId: 'MH',
    impactScore: 340,
    resourceId: 'SWVIC07',
    resourceName: 'Copper Cell 7',
    division: 'Complex Engineering',
    postCode: 'CF72 9AJ',
    updatedAt: '2026-01-02T22:40:00Z',
  },
  {
    taskId: 'RG-QE998411',
    status: 'ISS',
    primarySkill: 'OGGA1',
    capabilities: ['OGGA1', 'OGGA2'],
    responseCode: 'SHP3',
    linkedTask: 'Y',
    commitType: 'TAIL',
    commitDate: '2026-01-05T00:00:00Z',
    workId: 'OGGA0155123',
    domainId: 'ZE',
    impactScore: 210,
    resourceId: 'SWKLY04',
    resourceName: 'Night Ops 04',
    division: 'Complex Engineering',
    postCode: 'CF38 2PT',
    updatedAt: '2026-01-02T18:20:00Z',
  },
  {
    taskId: 'RG-XH731045',
    status: 'EXC',
    primarySkill: 'FED1',
    capabilities: ['FED1', 'RFTTP'],
    responseCode: 'SH04',
    linkedTask: 'N',
    commitType: 'COMPLETE BY',
    commitDate: '2026-01-09T00:00:00Z',
    workId: 'OGEA0179900',
    domainId: 'MF',
    impactScore: 430,
    resourceId: 'SWCTL29',
    resourceName: 'Fiber Fast 29',
    division: 'Service Delivery',
    postCode: 'CF35 6HY',
    updatedAt: '2026-01-03T04:10:00Z',
  },
  {
    taskId: 'RG-JS119804',
    status: 'COM',
    primarySkill: 'SOGEA',
    capabilities: ['SOGEA', 'RFTTP'],
    responseCode: 'NONE',
    linkedTask: 'N',
    commitType: 'COMPLETE BY',
    commitDate: '2026-01-04T00:00:00Z',
    workId: 'SOGE0190321',
    domainId: 'ZA',
    impactScore: 150,
    resourceId: 'SWANK03',
    resourceName: 'QA Cell 03',
    division: 'Admin',
    postCode: 'CF11 9AB',
    updatedAt: '2026-01-01T23:55:00Z',
  },
]
