export type WorkingStatus = 'Signed on' | 'Signed on no work' | 'Not Signed on' | 'Absent' | 'Rostered off'
export type WorkPreference = 'X' | 'B' | 'U' // (X) Default, (B) Batches, (U) Underground
export type DomainId = 'ZA' | 'ZB' | 'ZC' | 'ZE' | 'MG' | 'MF' | 'MH'

export interface ResourceTableRow {
  resourceId: string
  resourceName: string
  scheduleShift: string
  startTime: string
  endTime: string
  homeLatitude: number
  homeLongitude: number
  division: 'Service Delivery' | 'Complex Engineering' | 'Admin'
  workingStatus: WorkingStatus
  domainId: DomainId
  ecbt: string // Engineer Committed By Time - currently set to shift start
  workPreference: WorkPreference
}

// Generated realistic engineer names and data based on unique resource IDs from Task Table
export const RESOURCE_TABLE_ROWS: ResourceTableRow[] = [
  {
    resourceId: 'SWBXR36',
    resourceName: 'Brandon Reed',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6521,
    homeLongitude: -3.3201,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '07:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQJX19',
    resourceName: 'Adam Jones',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7856,
    homeLongitude: -3.5825,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWBLN04',
    resourceName: 'Charlotte Miller',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6401,
    homeLongitude: -3.5012,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWZTR08',
    resourceName: 'Daniel Thompson',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.7989,
    homeLongitude: -3.3801,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '07:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWMME21',
    resourceName: 'Emma Wilson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6678,
    homeLongitude: -3.3189,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWAVE11',
    resourceName: 'Fiona Davies',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7723,
    homeLongitude: -3.5956,
    division: 'Service Delivery',
    workingStatus: 'Not Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWVIC07',
    resourceName: 'George Harrison',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6267,
    homeLongitude: -3.6023,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '07:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWKLY04',
    resourceName: 'Hannah Clarke',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.8034,
    homeLongitude: -3.3912,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWCTL29',
    resourceName: 'Ian Roberts',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6745,
    homeLongitude: -3.2878,
    division: 'Service Delivery',
    workingStatus: 'Absent',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWANK03',
    resourceName: 'Jessica Brown',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.7612,
    homeLongitude: -3.6190,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '07:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWKIL02',
    resourceName: 'Kevin Anderson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6389,
    homeLongitude: -3.3145,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWZED14',
    resourceName: 'Laura Martinez',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7956,
    homeLongitude: -3.5701,
    division: 'Service Delivery',
    workingStatus: 'Rostered off',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWPCM17',
    resourceName: 'Michael Taylor',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6598,
    homeLongitude: -3.6123,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '07:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWFLE05',
    resourceName: 'Natalie Green',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.8123,
    homeLongitude: -3.3567,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQAC12',
    resourceName: 'Oliver Hughes',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6534,
    homeLongitude: -3.5889,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWGLS33',
    resourceName: 'Patricia White',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.7845,
    homeLongitude: -3.3234,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '07:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWPRB06',
    resourceName: 'Quinn Jackson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6467,
    homeLongitude: -3.2912,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWRBI18',
    resourceName: 'Rachel Lewis',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7701,
    homeLongitude: -3.6045,
    division: 'Service Delivery',
    workingStatus: 'Not Signed on',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWISC22',
    resourceName: 'Samuel Walker',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6278,
    homeLongitude: -3.5401,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '07:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWQAT10',
    resourceName: 'Tara Phillips',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.8134,
    homeLongitude: -3.4078,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWLTN41',
    resourceName: 'Umar Ahmed',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6612,
    homeLongitude: -3.3056,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWCBR18',
    resourceName: 'Victoria Scott',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.7856,
    homeLongitude: -3.5912,
    division: 'Service Delivery',
    workingStatus: 'Absent',
    domainId: 'ZE',
    ecbt: '07:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWISD31',
    resourceName: 'William Bennett',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6389,
    homeLongitude: -3.6123,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWSYN12',
    resourceName: 'Yasmin Patel',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.8045,
    homeLongitude: -3.3689,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQAX05',
    resourceName: 'Zachary Turner',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6523,
    homeLongitude: -3.3167,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MF',
    ecbt: '07:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWBZT26',
    resourceName: 'Amelia Cooper',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7767,
    homeLongitude: -3.5834,
    division: 'Service Delivery',
    workingStatus: 'Rostered off',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWJUP14',
    resourceName: 'Benjamin Morris',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6334,
    homeLongitude: -3.5701,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWCLF19',
    resourceName: 'Chloe Edwards',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.8101,
    homeLongitude: -3.4012,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '07:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWVPR25',
    resourceName: 'David Campbell',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6678,
    homeLongitude: -3.2945,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWQAC18',
    resourceName: 'Ella Richardson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7956,
    homeLongitude: -3.6078,
    division: 'Service Delivery',
    workingStatus: 'Not Signed on',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWLNK02',
    resourceName: 'Frank Morgan',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6489,
    homeLongitude: -3.5590,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '07:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWORN08',
    resourceName: 'Grace Collins',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.8023,
    homeLongitude: -3.3356,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWISN11',
    resourceName: 'Henry Bell',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6312,
    homeLongitude: -3.3123,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWWAV44',
    resourceName: 'Isla Murphy',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.7745,
    homeLongitude: -3.5967,
    division: 'Service Delivery',
    workingStatus: 'Absent',
    domainId: 'ZC',
    ecbt: '07:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQAC30',
    resourceName: 'James Kelly',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6534,
    homeLongitude: -3.6089,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWBLT18',
    resourceName: 'Katie Bailey',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.8167,
    homeLongitude: -3.3912,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWCMB13',
    resourceName: 'Liam Carter',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.6698,
    homeLongitude: -3.2834,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '07:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWPNX09',
    resourceName: 'Mia Foster',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7856,
    homeLongitude: -3.6145,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWHRT04',
    resourceName: 'Noah Price',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.6378,
    homeLongitude: -3.5401,
    division: 'Service Delivery',
    workingStatus: 'Rostered off',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWQAC27',
    resourceName: 'Olivia Ward',
    scheduleShift: 'Early Shift',
    startTime: '07:00',
    endTime: '15:00',
    homeLatitude: 51.8034,
    homeLongitude: -3.3478,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '07:00',
    workPreference: 'X',
  },
]
