export type WorkingStatus = 'Signed on' | 'Signed on no work' | 'Not Signed on' | 'Absent' | 'Rostered off'
export type WorkPreference = 'X' | 'B' | 'U' // (X) Default, (B) Batches, (U) Underground
export type DomainId = 'ZA' | 'ZB' | 'ZC' | 'ZE' | 'MG' | 'MF' | 'MH'

export interface ResourceTableRow {
  resourceId: string
  resourceName: string
  scheduleShift: string
  startTime: string
  endTime: string
  homeLatitude: number
  homeLongitude: number
  division: 'Service Delivery' | 'Complex Engineering' | 'Admin'
  workingStatus: WorkingStatus
  domainId: DomainId
  ecbt: string // Engineer Committed By Time - currently set to shift start
  workPreference: WorkPreference
}

// Generated realistic engineer names and data based on unique resource IDs from Task Table
export const RESOURCE_TABLE_ROWS: ResourceTableRow[] = [
  {
    resourceId: 'SWBXR36',
    resourceName: 'Brandon Reed',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.724213,
    homeLongitude: -3.460506,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '06:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQJX19',
    resourceName: 'Adam Jones',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7156,
    homeLongitude: -3.4425,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWBLN04',
    resourceName: 'Charlotte Miller',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7201,
    homeLongitude: -3.4512,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'ZB',
    ecbt: '14:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWZTR08',
    resourceName: 'Daniel Thompson',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7089,
    homeLongitude: -3.4301,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '06:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWMME21',
    resourceName: 'Emma Wilson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7178,
    homeLongitude: -3.4389,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWAVE11',
    resourceName: 'Fiona Davies',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7223,
    homeLongitude: -3.4456,
    division: 'Service Delivery',
    workingStatus: 'Not Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWVIC07',
    resourceName: 'George Harrison',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7167,
    homeLongitude: -3.4523,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '06:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWKLY04',
    resourceName: 'Hannah Clarke',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7134,
    homeLongitude: -3.4412,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWCTL29',
    resourceName: 'Ian Roberts',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7245,
    homeLongitude: -3.4378,
    division: 'Service Delivery',
    workingStatus: 'Absent',
    domainId: 'MG',
    ecbt: '14:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWANK03',
    resourceName: 'Jessica Brown',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7112,
    homeLongitude: -3.4490,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '06:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWKIL02',
    resourceName: 'Kevin Anderson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7189,
    homeLongitude: -3.4345,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWZED14',
    resourceName: 'Laura Martinez',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7156,
    homeLongitude: -3.4501,
    division: 'Service Delivery',
    workingStatus: 'Rostered off',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWPCM17',
    resourceName: 'Michael Taylor',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7198,
    homeLongitude: -3.4423,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '06:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWFLE05',
    resourceName: 'Natalie Green',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7123,
    homeLongitude: -3.4367,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQAC12',
    resourceName: 'Oliver Hughes',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7234,
    homeLongitude: -3.4489,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'ZA',
    ecbt: '14:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWGLS33',
    resourceName: 'Patricia White',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7145,
    homeLongitude: -3.4534,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '06:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWPRB06',
    resourceName: 'Quinn Jackson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7167,
    homeLongitude: -3.4312,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWRBI18',
    resourceName: 'Rachel Lewis',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7201,
    homeLongitude: -3.4445,
    division: 'Service Delivery',
    workingStatus: 'Not Signed on',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWISC22',
    resourceName: 'Samuel Walker',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7178,
    homeLongitude: -3.4401,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '06:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWQAT10',
    resourceName: 'Tara Phillips',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7134,
    homeLongitude: -3.4478,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWLTN41',
    resourceName: 'Umar Ahmed',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7212,
    homeLongitude: -3.4356,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '14:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWCBR18',
    resourceName: 'Victoria Scott',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7156,
    homeLongitude: -3.4512,
    division: 'Service Delivery',
    workingStatus: 'Absent',
    domainId: 'ZE',
    ecbt: '06:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWISD31',
    resourceName: 'William Bennett',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7189,
    homeLongitude: -3.4423,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWSYN12',
    resourceName: 'Yasmin Patel',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7145,
    homeLongitude: -3.4389,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQAX05',
    resourceName: 'Zachary Turner',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7223,
    homeLongitude: -3.4467,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MF',
    ecbt: '06:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWBZT26',
    resourceName: 'Amelia Cooper',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7167,
    homeLongitude: -3.4334,
    division: 'Service Delivery',
    workingStatus: 'Rostered off',
    domainId: 'MF',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWJUP14',
    resourceName: 'Benjamin Morris',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7134,
    homeLongitude: -3.4501,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '14:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWCLF19',
    resourceName: 'Chloe Edwards',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7201,
    homeLongitude: -3.4412,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '06:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWVPR25',
    resourceName: 'David Campbell',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7178,
    homeLongitude: -3.4445,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWQAC18',
    resourceName: 'Ella Richardson',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7156,
    homeLongitude: -3.4378,
    division: 'Service Delivery',
    workingStatus: 'Not Signed on',
    domainId: 'ZA',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWLNK02',
    resourceName: 'Frank Morgan',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7189,
    homeLongitude: -3.4490,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '06:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWORN08',
    resourceName: 'Grace Collins',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7123,
    homeLongitude: -3.4356,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZB',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWISN11',
    resourceName: 'Henry Bell',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7212,
    homeLongitude: -3.4423,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZC',
    ecbt: '14:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWWAV44',
    resourceName: 'Isla Murphy',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7145,
    homeLongitude: -3.4467,
    division: 'Service Delivery',
    workingStatus: 'Absent',
    domainId: 'ZC',
    ecbt: '06:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWQAC30',
    resourceName: 'James Kelly',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7234,
    homeLongitude: -3.4389,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWBLT18',
    resourceName: 'Katie Bailey',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7167,
    homeLongitude: -3.4512,
    division: 'Service Delivery',
    workingStatus: 'Signed on no work',
    domainId: 'ZE',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWCMB13',
    resourceName: 'Liam Carter',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7198,
    homeLongitude: -3.4334,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '06:00',
    workPreference: 'B',
  },
  {
    resourceId: 'SWPNX09',
    resourceName: 'Mia Foster',
    scheduleShift: 'Day Shift',
    startTime: '08:00',
    endTime: '16:00',
    homeLatitude: 51.7156,
    homeLongitude: -3.4445,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MG',
    ecbt: '08:00',
    workPreference: 'X',
  },
  {
    resourceId: 'SWHRT04',
    resourceName: 'Noah Price',
    scheduleShift: 'Late Shift',
    startTime: '14:00',
    endTime: '22:00',
    homeLatitude: 51.7178,
    homeLongitude: -3.4401,
    division: 'Service Delivery',
    workingStatus: 'Rostered off',
    domainId: 'MF',
    ecbt: '14:00',
    workPreference: 'U',
  },
  {
    resourceId: 'SWQAC27',
    resourceName: 'Olivia Ward',
    scheduleShift: 'Early Shift',
    startTime: '06:00',
    endTime: '14:00',
    homeLatitude: 51.7134,
    homeLongitude: -3.4478,
    division: 'Service Delivery',
    workingStatus: 'Signed on',
    domainId: 'MH',
    ecbt: '06:00',
    workPreference: 'X',
  },
]
